# Generated by Django 3.2.3 on 2021-06-02 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0002_auto_20210602_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='taskmanager.userpic'),
        ),
        migrations.AlterField(
            model_name='userpic',
            name='profile_pic',
            field=models.ImageField(blank=True, default='../static/images/user.png', upload_to='users_pics/'),
        ),
    ]
