# Generated by Django 3.2.3 on 2021-06-02 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0004_alter_userinfo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='userpic',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
